no_color: False
aws_profile: <FILL THIS IN>
aws_region: "us-east-1"
user_public_ip: "DEFAULT_VALUE"
vpc_name: "LambdaFS_VPC"

security_group_name: "lambda-fs-security-group"
eks_cluster_name : "lambda-fs-eks-cluster"
eks_iam_role_name: "lambda-fs-eks-cluster-role"

ssh_keypair_name: <FILL THIS IN>
ssh_key_path: <FILL THIS IN>
num_ndb_datanodes: 4
num_lambda_fs_zk_vms: 3

lfs_client_autoscaling_group_instance_type: "r5.4xlarge"
hopsfs_client_autoscaling_group_instance_type: "r5.4xlarge"
hopsfs_namenode_autoscaling_group_instance_type: "r5.4xlarge"
lfs_client_vm_instance_type: "r5.4xlarge"
ndb_manager_instance_type: "r5.4xlarge"
ndb_datanode_instance_type: "r5.4xlarge"
lambdafs_zk_instance_type: "r5.4xlarge"
hopsfs_client_vm_instance_type: "r5.4xlarge"

# Create the primary Lambda-FS client VM and experiment driver.
create_lambda_fs_client_vm: True
# Create the primary HopsFS client VM and experiment driver.
create_hops_fs_client_vm: True

# Start the ZooKeeper cluster. If you are not creating the VMs as well, then you need to pass a YAML list of 
# IPs via the "zk_node_public_IPs" YAML parameter.
#
# This would look like:
#
# zk_node_public_IPs:
#   - <IP1>
#   - <IP2>
#   - ... 
#
start_zookeeper_cluster: True
# Populate the ZooKeeper cluster with the data required by Lambda-FS.
populate_zookeeper_cluster: True 

# You only need to specify this argument if you've already setup the ZooKeeper cluster and just want to (e.g.,) start the cluster on the already-running VMs.
# See the comment above the `start_zookeeper_cluster` property for more details.
# zk_node_public_IPs:
# - <IP1>
# - <IP2>
# - <IP3>

# in megabytes. used 12000 in evaluation.
zookeeper_jvm_heap_size: 4000

# If True, create the MySQL NDB Cluster VMs (manager node and data nodes).
create_ndb_cluster: True
# If True, start the MySQL NDB Cluster VMs (manager node and data nodes).
start_ndb_cluster: True 

# If True, do NOT create the IAM role used by the AWS EKS cluster.
skip_iam_role_creation: False
# If True, do NOT create the VPC used by HopsFS and LambdaFS.
skip_vpc_creation: False
# If True, do NOT create the AWS EKS cluster.
skip_eks: False
# If True, do NOT create the ZooKeeper VMs (used by Lambda-FS).
skip_zookeeper_vm_creation: False
# If True, do NOT create the AWS EC2 Launch Templates used for the Lambda-FS and HopsFS client VMs.
skip_launch_templates: False
# If True, do NOT create the AWS EC2 Autoscaling Groups used for the Lambda-FS and HopsFS client VMs.
skip_autoscaling_groups: False